[package]
name = "l3"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.11.2"
clap = { version = "4.5.51", features = ["derive"] }
common = { version = "0.1.0", path = "../common" }
l2 = { version = "0.1.0", path = "../l2" }

[[bin]]
name = "L3"
path = "src/main.rs"
