[package]
name = "l2"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = "0.11.1"
clap = { version = "4.5.50", features = ["derive"] }
common = { version = "0.1.0", path = "../common" }
l1 = { version = "0.1.0", path = "../l1" }

[[bin]]
name = "L2"
path = "src/main.rs"
